# Site settings
title: e-motors
email: e.motors.ua@gmail.com
description: Перемотка электродвигателей > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://e-motors.com.ua/" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman